# Generated by Django 4.1.5 on 2023-01-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reporter',
        ),
    ]
